data:
  batch_size: 128
  num_workers: 4
  root: data/fer2013
loss:
  class_counts:
  - 3995
  - 436
  - 4097
  - 7215
  - 4965
  - 4830
  - 3171
  use_class_weights: true
network:
  dropout: 0.2353084713854247
  input_size: 48
  model: cnn
  num_classes: 7
seed: 97
train:
  checkpoint_dir: outputs/checkpoints/
  early_stop_patience: 4
  log_dir: outputs/logs
  lr: 0.009924944772807663
  num_epochs: 50
