Train:
  batch_size: 128
  learning_rate: 0.0001
  regularization_rate: 0.0005
  epochs: 5
  steps: [6, 8]
  warmup: 0
  momentum: 0.9
  gamma: 1
  debug: True

Model:
  type: CNN # TwoLayerNet or VanillaCNN or MyModel or ResNet-32
  save_best: True

data:
  imbalance: regular # regular or imbalance
  beta: 0.9999